# Generated by Django 2.2.3 on 2021-09-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210906_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='', max_length=200),
        ),
    ]
